# Generated by Django 5.1.1 on 2024-09-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='university_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='student',
            name='varsity_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
